#!/usr/bin/env bash

## Copyright (C) 2020-2023 Aditya Shakya <adi1090x@gmail.com>

# Import Current Theme
DIR="$HOME/.config/i3"
RASI="$DIR/theme/rofi/music.rasi"
spotify_player_path="$HOME/.cargo/bin/spotify_player"

# Theme Elements
status=$($spotify_player_path get key playback 2> /dev/null)
if [[ -z "$status" ]]; then
	prompt='Offline'
	mesg="MPD is Offline"
else
  prompt=$(echo "$status" | jq -r '.item.artists[0].name')
  mesg=$(echo "$status" | jq -r '.item.name')
fi

# Options
layout=`cat ${RASI} | grep 'USE_ICON' | cut -d'=' -f2`
is_playing=$(echo "$status" | jq -r '.is_playing')
if [[ "$layout" == 'NO' ]]; then
	if [[ "$is_playing" == "true" ]]; then
		option_1=" Pause"
	else
		option_1=" Play"
	fi
	option_2=" Stop"
	option_3=" Previous"
	option_4=" Next"
	option_5=" Repeat"
	option_6=" Random"
else
	if [[ "$is_playing" == "true" ]]; then
		option_1=""
	else
		option_1=""
	fi
	option_2=""
	option_3=""
	option_4=""
	option_5=""
	option_6=""
fi

# Toggle Actions
active=''
urgent=''
# Repeat
repeat_state=$(echo "$status" | jq -r '.repeat_state')
shuffle_state=$(echo "$status" | jq -r '.shuffle_state')
if [[ ${repeat_state} == "context" ]]; then
    active="-a 4"
elif [[ ${repeat_state} == "off" ]]; then
    urgent="-u 4"
else
    option_5=" Parsing Error"
fi
# Random
if [[  ${shuffle_state} == "true" ]]; then
    [ -n "$active" ] && active+=",5" || active="-a 5"
elif [[ ${shuffle_state} == "false" ]]; then
    [ -n "$urgent" ] && urgent+=",5" || urgent="-u 5"
else
    option_6=" Parsing Error"
fi

# Rofi CMD
rofi_cmd() {
	rofi -dmenu \
		-p "$prompt" \
		-mesg "$mesg" \
		${active} ${urgent} \
		-markup-rows \
		-theme ${RASI}
}

# Pass variables to rofi dmenu
run_rofi() {
	echo -e "$option_1\n$option_2\n$option_3\n$option_4\n$option_5\n$option_6" | rofi_cmd
}

# Execute Command
run_cmd() {
	if [[ "$1" == '--opt1' ]]; then
		$spotify_player_path playback play-pause
	elif [[ "$1" == '--opt2' ]]; then
		$spotify_player_path playback play-pause
		$spotify_player_path playback seek 0
	elif [[ "$1" == '--opt3' ]]; then
		$spotify_player_path playback previous
	elif [[ "$1" == '--opt4' ]]; then
		$spotify_player_path playback next
	elif [[ "$1" == '--opt5' ]]; then
		$spotify_player_path playback repeat
	elif [[ "$1" == '--opt6' ]]; then
		$spotify_player_path playback shuffle
	fi
}

# Actions
chosen="$(run_rofi)"
case ${chosen} in
    $option_1)
		run_cmd --opt1
        ;;
    $option_2)
		run_cmd --opt2
        ;;
    $option_3)
		run_cmd --opt3
        ;;
    $option_4)
		run_cmd --opt4
        ;;
    $option_5)
		run_cmd --opt5
        ;;
    $option_6)
		run_cmd --opt6
        ;;
esac
